http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  facility:
    host: localhost
    paths: '/facility/*'
  catering:
    host: localhost
    paths: '/catering/*'
serviceEndpoints:
  facility:
    url: 'http://localhost:3002/'
  catering:
    url: 'http://localhost:3000/'
policies: 
  - rewrite
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
pipelines:
  - name: catering
    apiEndpoints:
      - catering
    policies:
      -
        rewrite:
          -
            condition:
              name: regexpmatch
              match: ^/catering/(.*)$
            action:
              rewrite: /catering/$1
      - proxy:
          - action:
              serviceEndpoint: catering
              changeOrigin: true
  - name: facility
    apiEndpoints:
      - facility
    policies:
      - rewrite:
          - 
            condition:
                name: regexpmatch
                match: ^/facility/(.*)$
            action:
                rewrite: /facility/$1
      - proxy:
        - action:
            serviceEndpoint: facility
  